use_frameworks!

platform :ios, '9.0'

target 'MSYReadBundleFile_Example' do
  pod 'MSYReadBundleFile', :path => '../'

  target 'MSYReadBundleFile_Tests' do
    inherit! :search_paths

    
  end
end
